name: flutter_catalyst
version: 2.0.0
description: A dependency injection container which also supports autowiring of services.
homepage: https://github.com/mintware-de/flutter_catalyst
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  test: 1.16.8