name: flutter_catalyst
version: 1.0.2
description: A dependency injection container which also supports autowiring of services.
homepage: https://github.com/mintware-de/flutter_catalyst
environment:
  sdk: '>=2.6.0 <3.0.0'
dev_dependencies:
  test: 1.3.0